name: Robot Framework CI

on:
  push:
    branches:
      - develop
  # pull_request:
  # workflow_dispatch:

jobs:
    Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - uses: actions/cache@v2
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt
        
        - uses: browser-actions/setup-chrome@v1
        - run: chrome --version
        - uses: driver-actions/setup-chromedriver@v2
        - run: |
            export DISPLAY=:99
            chromedriver --url-base=/wd/hub &
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
            chromedriver --version
    
        - name: Run Test
          run: python -m robot --outputdir results testcases/
          
        - name: Run Test and create report
          run: python -m robot -d reports -x junit-report.xml "testcases/"
          
        - name: Run Robot Framework tests and generate report
          run: |
             echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
        # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
        #   if: env.ROBOT_RC != '0'
        #   run: |
        #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
        #     exit 1
        
        - name: Publish test results
          uses: actions/upload-artifact@v2
          with:
            name: robot-test-results
            path: results
